public enum Education {

    BACHELORS, SOME_COLLEGE, ELEVENTH, HS, PROF_SCHOOL, ASSOCACADEMY, ASSOCVOCATIONAL, NINTH, SEVENTH_EIGHTH, TWELFTH, MASTERS, FIRST_THRU_FOURTH, TENTH, DOCTORATE, FIFTH_SIXTH, PRESCHOOL;

}
