public enum NativeCountry {

    US, CAMBODIA, ENGLAND, PUERTO_RICO, CANADA, GERMANY, OUTLYING_US, INDIA, JAPAN, GREECE, SOUTH, CHINA,
    CUBA, IRAN, HONDURAS, PHILLIPINES, ITALY, POLAND, JAMAICA, VIETNAM, MEXICO, PORTUGAL, IRELAND, FRANCE,
    DR, LAOS, ECUADOR, TAIWAN, HAITI, COLUMBIA, HUNGARY, GUATAMALLA, NICARAGUA, SCOTLAND, THAILAND,
    YUGOSLAVIA, EL_SALVADOR, TRINIDAD, PERU, HK, HOLLAND;
}
