public enum Occupation {
    TECH_SUPPORT, CRAFT_REPAIR, OTHER_SERVICE, SALES, EXEC_MANAGERIAL, PROF_SPECIALTY, HANDLERS_CLEANERS,
    MACHINE_OP_INSPECT, ADMIN_CLINICAL, FARMING_FISHING, TRANSPOR_MOVING, PRIV_HOUSE_SERV,
    PROTECT_SERVICE, ARMOURED_SERVICE;
}
